SELECT 
		P.NMPESSOA                                      AS NMPESSOA
       , AR.CDAREAREGISTRO                                 as ddd
       ,LB.NRLINHA                                     AS NRLINHA
	   ,D.NRDOCUMENTO									AS DOCUMENTO
	, SOP.NMSISTEMAORIGEM                             	AS NMSISTEMAORIGEMPESSOA
	, SOL.NMSISTEMAORIGEM                               AS NMSISTEMAORIGEMLINHA    
	, (SELECT PC.DSCONTATO 
		 FROM CUSTOMER.PESSOACOMUNICACAO PC
		WHERE P.IDPESSOA=PC.IDPESSOA
		  AND REGEXP_LIKE( PC.DSCONTATO,'@')                    
		  AND PC.DTULTIMAALTERACAO = (SELECT MAX(PC.DTULTIMAALTERACAO)
											FROM CUSTOMER.PESSOACOMUNICACAO PC2                                            
										   WHERE IDTIPOCOMUNICACAO IN (12, 6, 1838, 2141)
											 AND PC2.IDPESSOA = P.IDPESSOA)) AS EMAIL


	, (SELECT PC.DSCONTATO 
		 FROM CUSTOMER.PESSOACOMUNICACAO PC
		WHERE P.IDPESSOA=PC.IDPESSOA
		  AND IDTIPOCOMUNICACAO IN (13,2,2140,9,7,8,3)                   
		  AND PC.DTULTIMAALTERACAO = (SELECT MAX(PC.DTULTIMAALTERACAO)
											FROM CUSTOMER.PESSOACOMUNICACAO PC2                                            
										   WHERE IDTIPOCOMUNICACAO IN (13,2,2140,9,7,8,3)
											 AND PC2.IDPESSOA = P.IDPESSOA)) AS CONTATO 

	, PF.DTNASCIMENTO                                AS DTNASCIMENTO
	, PF.NMMAE                                       AS NMMAE
	, PE.NRCEP                                       AS NRCEP    
	, PE.NMLOGRADOURO                                AS NMLOGRADOURO
	, PE.NRENDERECO                                  AS NRENDERECO
	, PE.DSENDERECOCOMPLEMENTO                       AS DSENDERECOCOMPLEMENTO
	, PE.NMBAIRRO									 AS NMBAIRRO
	, UF.SGUF                                        AS SGUF
	, PA.galho_tres                                  AS galho_tres
	, PE.NMMUNICIPIO                                 AS NMMUNICIPIO   
	, PA.NMPAIS                                      AS NMPAIS
	, TO_CHAR(P.DTULTIMAALTERACAO,'DD/MM/RRRR')      AS DTULTIMA_ALTERACAO_PESSOA
	FROM LINHA.LINHABASE LB
	JOIN APOIO.AREAREGISTRO AR ON (LB.IDAREAREGISTRO=AR.IDAREAREGISTRO)
	JOIN LINHA.LINHATELEFONICA LT ON (LT.IDLINHABASE=LB.IDLINHABASE)
	JOIN CUSTOMER.PESSOALINHA PL ON (PL.IDLINHATELEFONICA=LT.IDLINHATELEFONICA)
	JOIN CUSTOMER.PESSOADEPARA PP ON (PP.IDPESSOADEPARA=PL.IDPESSOADEPARA)
	JOIN CUSTOMER.PESSOA P ON (PP.IDPESSOA=P.IDPESSOA)        
	JOIN APOIO.SISTEMAORIGEM SOP ON (SOP.IDSISTEMAORIGEM=P.IDSISTEMAORIGEM)
	JOIN APOIO.SISTEMAORIGEM SOL ON (SOL.IDSISTEMAORIGEM=LT.IDSISTEMAORIGEM)

	/*Documento*/
	JOIN CUSTOMER.PESSOADOCUMENTO PD ON PD.IDPESSOA = P.IDPESSOA
	JOIN CUSTOMER.DOCUMENTO 	   D ON D.IDDOCUMENTO = PD.IDDOCUMENTO
	JOIN APOIO.TIPODOCUMENTO	  TD ON TD.IDTIPODOCUMENTO = D.IDTIPODOCUMENTO AND TD.SGCLASSIFICACAO IN ('CPF','CNPJ')

	/*Informacao na PESSOAFISICA nao e obrigatoria o cadastro*/
	LEFT JOIN CUSTOMER.PESSOAFISICA PF ON(PF.IDPESSOA=P.IDPESSOA)

	/*Nem todos os lagados cadastram o endereco, por isso nao pode ser obrigatorio.*/
	LEFT JOIN CUSTOMER.PESSOAENDERECO PE ON(PE.IDPESSOA=P.IDPESSOA AND PE.IDSISTEMAORIGEM=P.IDSISTEMAORIGEM)
	LEFT JOIN APOIO.PAIS PA ON (PA.IDPAIS=PE.IDPAIS)
	LEFT JOIN APOIO.UF UF ON (UF.IDUF=PE.IDUF)
    AND PL.IDTIPORELACIONAMENTO = 2;
    